mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from polls import views

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:thing_id>/', views.detail, name='detail'),
    path('vote/', views.vote, name='vote'),
    path('new/', views.new, name='new'),
    path('thingslist/', views.ThingsListView.as_view(), name='thingslist'),
    path('person/<int:person_id>/', views.person_detail, name='person_detail'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

NAME_CHOICES = (
    ('Jan', 'Jan'),
    ('Sam', 'Sam'),
    ('Radim', 'Radim'),
    ('Stepan', 'Stepan'),
)

class Person(models.Model):
    name = models.CharField(
        max_length=6
        )
    spendings = models.FloatField('spendings', default = 0)
    net_spendings = models.FloatField('net_spendings', default=0)

    def __str__(self):
        return self.name

class Thing(models.Model):
    thing_description = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    price = models.FloatField('price')
    found_price = models.FloatField('found_price', null=True)
    buyer = models.ForeignKey(
                Person,
                on_delete=models.SET_NULL,
                null=True
                )
    flag = models.IntegerField('flag', default=3)
    def __str__(self):
        return self.thing_description



''' class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text '''

polls/forms.py
from django.forms import ModelForm
from polls.models import Person

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name']

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import urllib.request
import json
from .models import Thing, Person


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        """
        Return actualised list of all persons.
        """
        overall_spendings = 0
        for person in Person.objects.all():
            overall_spendings += person.spendings
        for person in Person.objects.all():
            spendings = 0
            for thing in person.thing_set.all():
                spendings += thing.price
            person.spendings = spendings
            person.net_spendings = round((spendings - \
                (overall_spendings / Person.objects.count())), 2)
            person.save()
        return Person.objects.all()

class MenuListView(generic.ListView):
    template_name =  'polls/menu.html'
    context_object_name = 'person_list'
    def get_queryset(self):
        return Person.objects.all()

class ThingsListView(generic.ListView):
    template_name = 'polls/thingslist.html'
    context_object_name = 'latest_things_list'

    def get_queryset(self):
        """
        Return the last five published questions 
        (not including those set to be
        published in the future).
        """
        return Thing.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

def detail(request, thing_id):
    thing = get_object_or_404(Thing, pk=thing_id)
    return render(request, 'polls/detail.html', {'thing': thing, 'person_list': Person.objects.all()})


def person_detail(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    return render(request,
                  'polls/person_detail.html',
                  {'person': person,
                   "thing_set": person.thing_set.all(),
                   'person_list': Person.objects.all()})

    


def new(request):
    return render(
                request,
                'polls/new.html',
                {'thing': Thing, 'person_list': Person.objects.all()}
                ) 


CZK_to_EUR = 25.5
def vote(request):
    good = request.POST['thing_name']
    zboziURL = "https://www.zbozi.cz/api/v1/search?categoryLoadOffers=1&forceListProductsAndOffers=0&groupByCategory=0&groupByCategoryProductCount=4&loadTopProducts=false&page=1&query="
    with urllib.request.urlopen((zboziURL + good.replace(' ', '-'))) as url:
        data = json.loads(url.read().decode())
        meanPrice = 0
    try:
        for i in range(1, len(data['products']) + 1):
            meanPrice = meanPrice + data['products'][i - 1]['minPrice']
        meanPrice = meanPrice / (len(data['products']) + 1) / 100
        found_price = round(meanPrice, 2)
        flag = 1
    except:
        try:
            results = 0
            meanAppPrice = 0
            for i in range(1, len(data['priceRanges'])):
                results = results + data['priceRanges'][i - 1]['results']
                meanAppPrice = meanAppPrice + \
                    ((data['priceRanges'][i - 1]['minPrice'] + data['priceRanges']
                      [i - 1]['maxPrice']) / 2) * (data['priceRanges'][i - 1]['results'])
            meanAppPrice = meanAppPrice / results
            found_price = round(meanAppPrice, 2)
            flag = 2
        except:
            found_price = 0
            flag = 3
    p = Person.objects.get(pk=request.POST['buyer'])
    price = request.POST['thing_price']
    t = Thing(
        thing_description=good,
        pub_date=timezone.now(),
        price=price,
        found_price=round((found_price / CZK_to_EUR), 1),
        buyer=p,
        flag=flag
        )
    t.save()
    p.spendings += float(price)
    p.save()
    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/detail.html
{% include 'polls/menu.html' %}
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <div class="w3-main" style="margin-left:150px">

        <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">
                
                <h1 class="w3-text-teal">{{ thing.thing_description }}</h1>
                <br> Bought: {{ thing.buyer }}
                <br> Added: {{ thing.pub_date }}
                <br> Price: {{ thing.price }} EUR
                <br> {% if thing.flag == 1 %}
                <p>
                    <strong>Average price: {{ thing.found_price}} EUR</strong>
                </p>
                {% endif %} {% if thing.flag == 2 %}
                <p>
                    <strong>Approximate average price: {{ thing.found_price}} EUR</strong>
                </p>
                {% endif %} {% if thing.flag == 3 %}
                <p>
                    <strong>Price not found</strong>
                </p>
                {% endif %}
            </div>

        </div>
        <!-- -------------------------------------------------------------------------------- -->
        <!-- -------------------------------------------------------------------------------- -->
     {% include 'polls/footer.html' %}

polls/templates/polls/footer.html
<div class="w3-row">


</div>

<div class="w3-row w3-padding-64">


</div>

<!-- Pagination -->
<!-- <div class="w3-center w3-padding-32">
            <div class="w3-bar">
                <a class="w3-button w3-black" href="#">1</a>
                <a class="w3-button w3-hover-black" href="#">2</a>
                <a class="w3-button w3-hover-black" href="#">3</a>
                <a class="w3-button w3-hover-black" href="#">4</a>
                <a class="w3-button w3-hover-black" href="#">5</a>
                <a class="w3-button w3-hover-black" href="#">»</a>
            </div>
        </div> -->

<footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
        <h4>© K. J. van Garderen </h4>
    </div>

    <div class="w3-container w3-theme-l1">
        <p>Powered by
            <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a>
        </p>
    </div>
</footer>

<!-- END MAIN -->
</div>

<script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
            overlayBg.style.display = "none";
        } else {
            mySidebar.style.display = 'block';
            overlayBg.style.display = "block";
        }
    }

    // Close the sidebar with the close button
    function w3_close() {
        mySidebar.style.display = "none";
        overlayBg.style.display = "none";
    }
</script>

polls/templates/polls/index.html
{% include 'polls/menu.html' %}
<style>
    table {
        position: relative;
        border-collapse: collapse;
        width: 50%;
    }

    th,
    td {
        text-align: right;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    th {
        background-color: #4CAF50;
        color: white;
    }
</style>
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    

    <div class="w3-main" style="margin-left:150px">

        <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">
                <h1 class="w3-text-teal">Current spendings</h1>
                 {% if person_list %}
                
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Net:</th>
                        <th>Overall</th>
                    </tr>
                     {% for person in person_list %}
                    <tr>
                        <td><a href="{% url 'polls:person_detail' person.id %}">{{ person.name }}</a></td>
                        <td>{{person.net_spendings}} EUR</td>
                        <td>{{person.spendings}} EUR</td>
                    </tr>
                    
                    {% endfor %}
                    
                </table>
                
                {% else %}
                <p>No polls are available.</p>
                {% endif %}
            </div>
            
        </div>
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
     {% include 'polls/footer.html' %}

polls/templates/polls/menu.html
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    html,
    body,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: "Roboto", sans-serif;
    }

    .w3-sidebar {
        z-index: 3;
        width: 150px;
        top: 43px;
        bottom: 0;
        height: inherit;
    }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    html,
    body,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: "Roboto", sans-serif;
    }

    .w3-sidebar {
        z-index: 3;
        width: 152px;
        top: 43px;
        bottom: 0;
        height: inherit;
    }
</style>

<body>

    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()">
                <i class="fa fa-bars"></i>

                <a href="{% url 'polls:index' %}" class="w3-bar-item w3-button w3-theme-l1">Mortal Kombat</a>
                {% if person_list %} {% for person in person_list %} {% if person.net_spendings > 0 %}
                <a class="w3-bar-item w3-button w3-hide-small w3-light-green w3-hover-white" href="{% url 'polls:person_detail' person.id %}">
                    {{ person.name }}: {{person.net_spendings}}
                </a>
                {% else %}
                <a class="w3-bar-item w3-button w3-hide-small w3-deep-orange w3-hover-white" href="{% url 'polls:person_detail' person.id %}">
                    {{ person.name }}: {{person.net_spendings}}
                </a>
                {% endif %} {% endfor %} {% else %}
                <a class="w3-bar-item w3-button w3-hover-black">No added people.</a>
                {% endif %}
                <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'polls:new'%}">
                    New thing?</a>
                <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">About</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Values</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a> -->
        </div>
    </div>

    <!-- Sidebar -->
    <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large"
            title="Close Menu">
            <i class="fa fa-remove"></i>
        </a>
        <h4 class="w3-bar-item">
            <b>Menu</b>
        </h4>
        <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'polls:new'%}">New thing?</a>
        <br>
        <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'polls:thingslist'%}">List of things</a>


    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->

polls/templates/polls/new.html
{% include 'polls/menu.html' %}
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <div class="w3-main" style="margin-left:150px">

        <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">
                <h1 class="w3-text-teal">Add new thing</h1>
                <form action="{% url 'polls:vote' %}" method="post">
                    {% csrf_token %} Thing:
                    <input type="text" name="thing_name">
                    <br> Price:
                    <input type="float" name="thing_price"> EUR
                    <br> {% for human in person_list %}
                    <input type="radio" name="buyer" id="human{{ forloop.counter }}" value="{{ human.id }}">
                    <label for="human{{ forloop.counter }}">{{ human.name }}</label>
                    <br /> {% endfor %}
                    <br>
                
                    <input type="submit" value="Submit" />
                </form>
            </div>

        </div>
        <!-- -------------------------------------------------------------------------------- -->
        <!-- -------------------------------------------------------------------------------- -->
     {% include 'polls/footer.html' %}

polls/templates/polls/person_detail.html
{% include 'polls/menu.html' %}
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <div class="w3-main" style="margin-left:150px">

        <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">

                <h1 class="w3-text-teal">{{ person.name }}</h1>
                Spendings: {{person.spendings}} EUR <br>
                Net spendings: {{person.net_spendings}} EUR

                <br> bought:
                <br> {% for thing in thing_set %}
                <li>
                    <a href="{% url 'polls:detail' thing.id %}">{{ thing.thing_description }}</a> -- {{thing.price}}
                </li>
                {% endfor %}
            </div>

        </div>
        <!-- -------------------------------------------------------------------------------- -->
        <!-- -------------------------------------------------------------------------------- -->
     {% include 'polls/footer.html' %}

polls/templates/polls/thingslist.html
{% include 'polls/menu.html' %}
    <!-- -------------------------------------------------------------------------------- -->
    <!-- -------------------------------------------------------------------------------- -->
    <div class="w3-main" style="margin-left:150px">

        <div class="w3-row w3-padding-64">
            <div class="w3-twothird w3-container">

                <h1 class="w3-text-teal">History of purchases</h1>

                {% if latest_things_list %}
                <ul>
                    {% for thing in latest_things_list %}
                    <li>
                        <a href="{% url 'polls:detail' thing.id %}">{{ thing.thing_description }}</a>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <p>No polls are available.</p>
                {% endif %}
            </div>

        </div>
        <!-- -------------------------------------------------------------------------------- -->
        <!-- -------------------------------------------------------------------------------- -->
     {% include 'polls/footer.html' %}